BEGIN;
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Assembled in Mexico of US components', '');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Garment is made of imported fabric.', 'HECHO EN ... (COUNTRY) CON TELA IMPORTADA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN ARGENTINA', 'HECHO EN ARGENTINA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN AUSTRALIA', 'HECHO EN AUSTRALIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BAHRAIN', 'HECHO EN BAHREIN');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BANGKOK', '');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BANGLADESH', 'HECHO EN BANGLADESH');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BOTSWANA', 'HECHO EN BOTSWANA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BRAZIL', 'HECHO EN BRASIL');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BRUNEI', 'HECHO EN BRUNEI');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BRUNEI DARUSSALAM', 'HECHO EN BRUNEI DARUSSALAM');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN BULGARIA', 'HECHO EN BULGARIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN CAMBODIA', 'HECHO EN CAMBOYA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN CANADA', 'HECHO EN CANADA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN CHINA', 'HECHO EN CHINA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN COLUMBIA', 'HECHO EN COLOMBIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN COSTA RICA', 'HECHO EN COSTA RICA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN DJAKARTA', '');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN DOMINICAN REPUBLIC', 'HECHO EN REPUBLICA DOMINICANA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Made in Dominican Republic of U.S. fabric', 'HECHO EN REPUBLICA DOMINICANA CON TELA IMPORTADA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN EGYPT', 'HECHO EN EGIPTO');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN EL SALVADOR', 'HECHO EN EL SALVADOR');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN ENGLAND', 'HECHO EN INGLATERRA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN FIJI', 'HECHO EN FIDJI');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN FRANCE', 'HECHO EN FRANCIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN GREAT BRITAIN', 'HECHO EN LA GRAN BRETAÑA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN GREECE', 'HECHO EN GRECIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN GUATEMALA', 'HECHO EN GUATEMALA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN HAITI', 'HECHO EN HAITI');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN HONDURAS', 'HECHO EN HONDURAS');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Made in Honduras of U.S. fabric', 'HECHO EN HONDURAS CON TELA IMPORTADA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN HONG KONG', 'HECHO EN HONG KONG');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN HUNGARY', 'HECHO EN HUNGRIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN INDIA', 'HECHO EN INDIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Made in India with fabric of Ireland', 'HECHO EN INDIA CON TELA IMPORTADA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN INDONESIA', 'HECHO EN INDONESIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN IRELAND', 'HECHO EN IRLANDA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN ISRAEL', 'HECHO EN ISRAEL');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN JAMAICA', 'HECHO EN JAMAICA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN JAPAN', 'HECHO EN JAPON');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN JORDAN', 'HECHO EN JORDANIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN KOREA', 'HECHO EN COREA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN LESOTHO', 'HECHO EN LESOTHO');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MACAU', 'HECHO EN MACAO');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MADAGASCAR', 'HECHO EN MADAGASCAR');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MALAYSIA', 'HECHO EN MALASIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MALTA', 'HECHO EN MALTA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MAURITIUS', 'HECHO EN ISLAS MAURICIO');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MEXICO', 'HECHO EN MEXICO');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MOLDOVA', 'HECHO EN MOLDAVIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MONGOLIA', 'HECHO EN MONGOLIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN MOROCCO', 'HECHO EN MARRUECOS');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN NEPAL', 'HECHO EN NEPAL');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN NICARAGUA', 'HECHO EN NICARAGUA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN NORTHERN MARIANA ISLANDS (USA)', 'HECHO EN ISLAS MARIANAS DEL NORTE');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Made in Northern Mariana Islands (USA) of imported fabric', 'HECHO EN ISLAS MARIANAS DEL NORTE CON TELA IMPORTADA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN OMAN', 'HECHO EN OMAN');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN PAKISTAN', 'HECHO EN PAKISTAN');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN PANAMA', 'HECHO EN PANAMA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN PERU', 'HECHO EN PERU');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN PHILIPPINES', 'HECHO EN FILIPINAS');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN PORTUGAL', 'HECHO EN PORTUGAL');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN QATAR', 'HECHO EN QATAR');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN ROMANIA', 'HECHO EN RUMANIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN RUSSIA', 'HECHO EN RUSIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN SCOTLAND', 'HECHO EN ESCOCIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN SINGAPORE', 'HECHO EN SINGAPUR');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN SOUTH AFRICA', 'HECHO EN SUDAFRICA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN SPAIN', 'HECHO EN ESPAÑA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN SRI LANKA', 'HECHO EN SRI LANKA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN SULTANATE OF OMAN', 'HECHO EN OMAN');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN TAIWAN', 'HECHO EN TAIWAN');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN THAILAND', 'HECHO EN TAILANDIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN TUNISIA', 'HECHO EN TUNEZ');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN TURKEY', 'HECHO EN TURQUIA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN TURKMENISTAN', 'HECHO EN TURKMENISTAN');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN UNITED ARAB EMIRATES', 'HECHO EN EMIRATOS ARABES UNIDOS');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN UNITED KINGDOM', 'HECHO EN REINO UNIDO');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN URUGUAY', 'HECHO EN URUGUAY');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN USA', 'HECHO EN ESTADOS UNIDOS DE AMERICA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'Made in USA, Finished in Costa Rica', 'HECHO EN ESTADOS UNIDOS DE AMERICA');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN VIETNAM', 'HECHO EN VIETNAM');
INSERT INTO "master_co" ("active", "english", "spanish") VALUES (0, 'MADE IN ZIMBABWE', 'HECHO EN ZIMBAWE');
COMMIT;