BEGIN;
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'A4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'B4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'C4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'D4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'E4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'F4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'G4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'H4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'I4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'J4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'K4');
INSERT INTO "master_date_code" ("active", "val") VALUES (0, 'L4');
COMMIT;