BEGIN;
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'acetate', 'ACETATO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'acrylic', 'ACRILICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'African Cotton', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'ailanthus silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'all man made materials', 'todos los componentes hechos a mano');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'all new materials', 'NUEVOS MATERIALES');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'alpaca', 'ALPACA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'alpaca fur', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'anaphe silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'angora rabbit fur fiber', 'PELO DE ANGORA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'angora rabbit hair', 'PELO DE ANGORA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'AntronÃ‚Â® nylon', 'POLIAMIDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'aramid', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Argentine leather', 'CUERO ARGENTINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'azlon', 'azlon');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Azlon (From Soybean)', 'azlon (fibra sintética de soya)');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'bamboo', 'BAMBU');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'banana leaf fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'biconstituent fiber', 'fibra reconstituida');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'bleached lamb leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'bleached shearling lamb', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'bonded leather', 'cuero regenerado');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'brass', 'LATON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Calf hair', 'Pelo de becerro');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'calf leather', 'PIEL DE BECERRO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'calf split suede', 'gamuza');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'calf suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'calf suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'camel hair', 'PELO DE CAMELLO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'camphor silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cashmere', 'CACHEMIRA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cassava silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'chlorofibre', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'coated leather', 'recubierto de cuero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'coir', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'combed cotton', 'ALGODON PEINADO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cornhusk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cotton', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'COTTON', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cotton', 'ALGODON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cow fur', 'PELO DE VACA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cow leather', 'PIEL DE BOVINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cow leather nubuck', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cow leather trim', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cow suede', 'gamuza');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cowhide', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cuprammonium filament', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'cupro', 'CUPRO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'damaged/broken feathers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'deer suede leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'deer suede leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'deerskin', 'PIEL DE CIERVO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'deerskin nubuck', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down', 'PLUMAJE');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down (minimum ___ % down)', '_ % plumaje');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down and feather fibers', 'PLUMAS Y PLUMAJE');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down and feathers', 'PLUMAS Y PLUMAJE');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down and feathers (__% down __% feathers)', '_ % PLUMAJE - % PLUMAS');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down clusters', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'down fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'DYED CALF HAIR', 'Pelo teñido de becerro');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'dyed Icelandic shearling lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'dyed Italian shearling lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'dyed Korean shearling lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'DYED MONGOLIAN SHEARLING LAMB', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'dyed shearling lamb', 'piel de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'dyed Spanish shearling lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Dyed Turkish Shearling Lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'dyed Uruguayan shearling lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'ECLONÂ® NYLON', 'ECLON NYLON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'EELSKIN', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'elastane', 'ELASTANO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'elasterell-p', 'elasterell-p');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'elastodiene', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'elastoester', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'elastomultiester', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'eri silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'ethyl vinyl acetate', 'ETIL VINIL ACETATO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'ethylene-vinyl acetate copolymer', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'EVA', 'etileno-acetato de vinilo');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of crotch', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of decoration', 'excluyendo la decoracion');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of decoration and elastic', 'excluyendo decoracion y elastico');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of elastic', 'excluyendo el elastico');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of embroidery', 'EXCLUYENDO EL BORDADO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Exclusive of faux fur decoration', 'DECORACION: PELO SINTETICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of metallic decoration', 'EXCLUYENDO DECORACION');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of ornamentation', 'EXCLUYENDO LA DECORACION');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of rubber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of spandex in cuff', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'exclusive of trim', 'excluyendo el adorno');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'feathers', 'PLUMAS');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'feathers and down', 'plumas y plumaje');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'fill', 'RELLENO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'flax', 'Lino');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine alligator skin', 'PIEL DE COCODRILO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Genuine Buffalo leather', 'piel de búfalo');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine calf leather', 'PIEL DE BECERRO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine calf suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine cow leather', 'PIEL DE BOVINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine cow suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine cowhide', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Genuine Goat Leather', 'PIEL DE CAPRINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine goat suede', 'PIEL DE CAPRINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine lamb leather', 'PIEL DE CORDERO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine lamb suede', '-% PIEL DE CORDERO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine lambskin', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine leather', 'PIEL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine leather trim', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine lizard skin', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine nubuck leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine pig leather', 'PIEL DE PORCINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine sheep leather', 'PIEL DE OVINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'glass fibers', 'FIBRA DE VIDRIO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'goat leather', 'PIEL DE CAPRINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'goat suede', 'PIEL DE CAPRINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'goose down', 'PLUMAJE DE GANSO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'goose down (minimum __ % down)', '_% PLUMAJE DE GANSO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'grey duck down', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'grey goose down', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'hemp', 'cáñamo');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'hi-bulk acrylic', 'ACRILICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Horse hair', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'horse leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'imitation leather', 'IMITACION PIEL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'imitation suede', 'GAMUZA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Italian leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Italian Merino Wool', 'LANA MERINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'jute', 'YUTE');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Kangaroo leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Kenaf', 'Kenaf');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Korean leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lamb leather', 'PIEL DE CORDERO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lamb nappa', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lambs'' wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lambskin', 'piel de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lambsuede', 'piel de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'landfowl feather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lastol', 'LASTOL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'leather', 'CUERO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'leather and man made materials', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'leather fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'linen', 'LINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'LurexÂ® metallic', 'LUREX');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'LycraÂ® Elasterell-p', 'ELASTANO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'LycraÂ® spandex', 'ELASTANO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lyocell', 'LYOCELL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'man made textile material', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'man-made materials', 'hecho a mano');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'mercerized cotton', 'ALGODON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'merino extra fine Italian wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'merino extra fine wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'merino wool', 'LANA MERINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'MerylÂ® Nylon', 'POLIAMIDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'metal fiber', 'METAL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'metallic', 'METALICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'metallic fiber', 'FIBRA METALICA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'metallized fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'micro TactelÂ® nylon', 'MICRO TACTEL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'MicrosupremeÃƒâ€šÃ‚Â® Acrylique', 'ACRILICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'minimum _% down', '_% PLUMAJE');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'modacrylic', 'MODACRILICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'modal', 'MODAL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'modal microfiber', 'MODAL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'mohair', 'PELO FINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Mulberry silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'multiconstituent fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'natural Argentine shearling lamb', 'Teñido de cordero');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'natural materials', 'MATERIALES NATURALES');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'neoprene', 'neopreno');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'new material', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'New Zealand leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Nickel silver', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'NON-LEATHER SUBSTANCES', 'SIN CUERO O DERIVADOS');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'non-textile', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'NUPLEX NYLON', 'POLIAMIDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'NYLON', 'POLIAMIDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'olefin', 'olefina');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organic', 'ORGANICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organic cotton', 'Algodon Organico');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organic linen', 'Lino Orgánico');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organic merino wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organic wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organically grown cotton', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'organically grown merino wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Organically grown wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other elements', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber', 'OTRAS FIBRAS');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (azlon)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (chlorofibre)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (elastodiene)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (elastoester)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (jute)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (lyocell)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (modal)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (rubber)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (triacetate)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fiber (vinyon)', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other fibers', 'OTRAS FIBRAS');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'other materials', 'OTROS MATERIALES');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'outer sole: mixture of rubber and synthetic resins', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'outer sole: rubber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Pakistani Leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'palm leaf', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'paper', 'PAPEL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'PAPER STRAW', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'patent polyurethane', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'PET', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'pig leather', 'PIEL DE PORCINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'pig suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'pig suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'pigskin', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Pima Cotton', 'ALGODON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'PLA', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'plastic', 'PLASTICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'plastic pellets', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyacetate', 'POLIACETATO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'POLYACRYLATES', 'POLIACRITALO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyacrylic resin', 'POLIACRILICO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyacrylonitrile synthetic fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyamide', 'POLIAMIDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polycarbonate', 'POLICARBONATO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyester', 'POLIESTER');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyester microfiber', 'POLIESTER');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyethylene', 'POLIETILENO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyethylene foam', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Polyethylene Vinyl Acetate', 'Polietileno Vinil Acetato');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polylactide fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polypropylene', 'POLIPROPILENO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polypropylene filament', 'FILAMENTO DE POLIPROPILENO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polypropylene synthetic fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polystyrene', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polystyrene foam', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyurethane', 'POLIURETANO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyurethane foam', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyurethane foam', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyurethane synthetic fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyvinyl', 'POLIVINILO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyvinyl acetate', 'acetato de polivinilo');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyvinyl chloride', 'CLORURO DE POLIVINILO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'promix fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Protein', 'Proteinas');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'pvc', 'CLORURO DE VINILO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'rabbit hair', 'PELO DE CONEJO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'raffia', 'RAFIA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'ramie', 'RAMIO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'rattan', 'RATAN');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'rayon', 'RAYON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Rayon (from bamboo)', 'Viscosa (de bamboo)');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'reclaimed cotton', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'reclaimed wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled cashmere', 'CACHEMIRA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled cotton', 'ALGODÓN RECICLADO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled polyester', 'Poliéster reciclado');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled polyethylene terephthalate bottle fabric', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled/reprocessed', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'resin', 'RESINA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'rubber', 'CAUCHO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'shearling lamb', 'piel de borrego con lana""');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'sheep leather', 'PIEL DE OVINO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'sheepskin', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'sheepskin suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'sheepskin suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'shetland wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'silicon', 'SILICON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'silicone', 'SILICON');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'silk', 'SEDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'SILK', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'SILK', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'simulated leather', 'PIEL SINTETICA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'simulated lizardskin grain', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'spandex', 'ELASTANO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'spandex exclusive of crotch and waistband', 'ELASTANO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Spanish leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'split hide cow leather', 'piel de vaca');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'SSS', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'SSS', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'straw', 'PAJA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'superfine alpaca', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'SupplexÂ® Nylon', 'POLIAMIDA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'SYNTHETIC', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'synthetic leather', 'PIEL SINTETICA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'synthetic leather trim', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TactelÂ® Nylon', 'TACTEL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'tempesti wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Tencel® lyocell', 'LYOCELL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'test', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST1', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST111', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST2', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST2', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'test222', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST3', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST3', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TEST333', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'textile', 'TEXTIL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'textile', 'TEXTIL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'ThinsulateÃ¢â€žÂ?', 'INSULACION');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'top grain cow leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'top grain cow suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'top grain lamb leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'TRACE AMOUNT OF OTHER FIBERS', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'triacetate', 'TRIACETATO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Tussah silk', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'UK leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'unknown recycled fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'unspecified fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Uruguayan leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'VINYL', 'VINIL');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'vinylon fibers', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'vinyon', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'virgin wool', 'LANA VIRGEN');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'viscose', 'VISCOSA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Viscose (from bamboo)', 'VISCOSA (DE BAMBOO)');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'viscose rayon', 'RAYON VISCOSA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'water buffalo leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'waterfowl feathers', 'PLUMA DE GANSO');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'waterfowl feathers and fiber', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'WAX', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'white duck down', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'white goose down', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Wood', 'MADERA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'wood cellulose', 'MADERA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'worsted merino wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'worsted wool', 'LANA');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'yak fur', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'yak hair', 'pelo de yak');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'zinc', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'alpaca fur', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'bleached lamb leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled/reprocessed', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'sheepskin', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'superfine alpaca', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'tempesti wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Wood', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'all man made materials', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'alpaca fur', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'bleached lamb leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'deer suede leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine calf leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine goat suede', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'genuine sheep leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'lamb leather', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'polyurethane foam', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'recycled/reprocessed', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'sheepskin', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'superfine alpaca', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'tempesti wool', '');
INSERT INTO "master_fibers" ("active", "english", "spanish") VALUES (0, 'Wood', '');
COMMIT;